config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {
      sessions: 'users/sessions',
      registrations: 'users/registrations'
  }
  resources :books, path: "books" do
    collection do
      get :newest
      get :price_asc
      get :price_desc
      get :name_a_to_z
      get :name_z_to_a
    end
  end

    resources :books, only: :show do
      resources :reviews, only: :create
    end

  resources :categories, only: [:index, :show]
  resources :order_items, only: [:index, :create, :update, :destroy]
  resources :orders, only: [:index, :create, :destroy]
  resources :checkout
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'dashboard#index'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)

    # Define abilities for the passed in user here. For example:
    user ||= User.new # guest user (not logged in)
    #if user.admin?
    #  can :manage, :all
    #else
      can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  validates :first_name, :last_name, :biography, presence: true
  has_many :books
end

app/models/book.rb
# frozen_string_literal: true

class Book < ApplicationRecord

  belongs_to :author
  belongs_to :category
  has_many :ratings
  has_many :order_items

  validates :title, :description, :price, :in_stock, presence: true

  mount_uploader :cover, CoverUploader

  scope :newest, -> { order(created_at: :desc) }
  scope :price_asc, -> { order(:price) }
  scope :price_desc, -> { order(price: :desc) }
  scope :by_title_asc,  -> { order(title: :asc) }
  scope :by_title_desc, -> { order(title: :desc) }
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :books
  validates :title, presence: true, uniqueness: true
end

app/models/coupon.rb
class Coupon < ApplicationRecord
  belongs_to :order, optional: true

  validates :number, presence: true, uniqueness: true
  validates :discount, presence: true
end

app/models/credit_card.rb
class CreditCard < ApplicationRecord
  has_one :order
  validates :number, :cvv, :expiration_month, :expiration_year, :first_name, :last_name, presence: true
end

app/models/delivery_info.rb
class DeliveryInfo < ApplicationRecord
  belongs_to :user
  validates :first_name,
            :last_name,
            :street_1,
            :zip_code,
            :city,
            :region,
            :phone,
            :country, presence: true
  validates :user, presence: true
end

app/models/order.rb
class Order < ApplicationRecord
  include AASM

  belongs_to :user
  belongs_to :credit_card, optional: true
  belongs_to :delivery, optional: true
  belongs_to :billing_address, optional: true
  belongs_to :shipping_address, optional: true
  has_one :coupon, optional: true
  has_many :order_items

  def add_book(book_params)
    current_item = order_items.find_by(book_id: book_params[:book_id])

    if current_item
      current_item.quantity += order_items.find_by[book_id: book_params[:book_id]]
      current_item.save
    else
      order_items.create(
          book_id: book_params[:book_id],
          quantity: book_params[:quantity]
      )
    end
  end

  aasm column: :state do
    state :cart, initial: true
    state :in_delivery, after_enter: :send_confirmation
    state :delivered

    event :deliver do
      transitions from: :in_progress, to: :in_delivery
    end

    event :confirm do
      transitions from: :in_delivery, to: :delivered
    end
  end

  def discount
    coupon ? coupon.discount.to_d : 0
  end

  def calc_total_price
    return self.update(total_price: nil) if self.order_items.empty?
    price = self.order_items.map { |item| item.quantity*item.book.price }.inject(&:+)
    self.update(total_price: price - self.discount)
  end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  include AASM

  belongs_to :book
  belongs_to :order

  validates :quantity, presence: true
  validates :book, presence: true
  validates :order, presence: true

  def subtotal
    book.price * quantity
  end
end

app/models/rating.rb
class Rating < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/street_address.rb
class StreetAddress < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :orders
  has_many :ratings
  has_one :delivery_info
  #validates :name, presence: true
  validates :email, presence: true, format: { with: /.+@.+\..+/i }

  def current_order
    orders.find_or_create_by(state: :cart)
  end

  def load_delivery_info
    return delivery_info if delivery_info.present?
    build_delivery_info
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  load_and_authorize_resource

  def index
    @items = current_order.order_items.preload(:book).map(&:decorate)
    @decorated_order = current_order.decorate
  end

  def show
  end
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/orders/index.html.haml
%main.container.general-main-wrap
  %p1
    %h1.general-title-margin Cart
    - if @items.count == 0
      %br
      %p1
        = t('cart.empty_cart')
      %br
        .text-center
          = link_to t('cart.back_to_store'), root_path, class: 'btn btn-default mb-20'
    - else
      .hidden-xs
        %table.table.table-hover
          %tr.no-hover
            %th.col-pic.pl-0
              %span.in-grey-600 Product
            %th.col-title
            %th.col-price
              %span.in-grey-600 Price
            %th.col-quantity
              %span.in-grey-600 Quantity
            %th.col-total
              %span.in-grey-600 SubTotal
            %th.col-close
          - @items.each do |order_item|
            %tr{ id: "order-item-#{order_item.id}" }
              %td
                .general-img-wrap-table
                  %img.cart-img-shadow.pull-left{src: "http://jonathantweedy.com/resources/thumbs/SmashingBook5ResponsiveWebDesign.jpg", alt: "design-book"}
              %td
                %a{ href: "#{book_url(order_item.book_id)}" }
                  %p.title
                    = order_item.title
              %td
                %span.font-16.in-gold-500
                  = order_item.price
              %td
                .input-group
                  %a.input-link{href: "#"}
                    %i.fa.fa-minus.line-heaght-40
                  %input.form-control.quantity-input{type: "text", value: "#{order_item.quantity}"}
                  %a.input-link{href: "#"}
                    %i.fa.fa-plus.line-heaght-40
              %td
                %span.font-16.in-gold-500
                  = order_item.subtotal
              %td
                = button_to order_item_url(order_item.id), class: 'close general-cart-close', method: :delete do
                  %span{'aria-hidden': "true"} &times;
  .general-order-wrap
    .row
      .col-sm-4
        .input-group.general-input-group
          %label.input-label Enter Your Coupon Code
          %input.form-control.mb-30{type: "text", placeholder: "Enter Your Coupon Code "}
          %div
            %button.btn.btn-primary.mr-5.mb-15 Apply Coupon
      .col-sm-8
        .res-mr-200.text-center.general-text-right
          %p.in-gold-500.font-18 Order Summary
          %table.general-summary-table.general-summary-table-right.general-text-right
            %tr
              %td
                %p.font-16 Subtotal:
              %td
                %p.font-16
                  = @decorated_order.subtotal
            %tr
              %td
                %p.font-16 Coupon:
              %td
                %p.font-16 €0.00
            %tr
              %td
                %strong.font-18 Order Total:
              %td
                %strong.font-18
                  = @decorated_order.total_with_coupon
          %button.btn.btn-default.mb-20.visible-xs-inline-block Checkout
  .text-center
    = link_to 'Checkout', checkout_path(:email_login), class: 'btn btn-default mb-20'
  //%button.btn.btn-default.mb-20.hidden-xs.center-block Checkout
  