config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {
      sessions: 'users/sessions',
      registrations: 'users/registrations'
  }
  resources :books, path: "books" do
    collection do
      get :newest
      get :price_asc
      get :price_desc
      get :name_a_to_z
      get :name_z_to_a
    end
  end

    resources :books, only: :show do
      resources :reviews, only: :create
    end

  resources :categories, only: [:index, :show]
  resources :order_items, only: [:index, :create, :update, :destroy]
  resources :orders, only: [:index, :create, :destroy]
  resources :checkout
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'dashboard#index'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)

    # Define abilities for the passed in user here. For example:
    user ||= User.new # guest user (not logged in)
    #if user.admin?
    #  can :manage, :all
    #else
      can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  validates :first_name, :last_name, :biography, presence: true
  has_many :books
end

app/models/book.rb
# frozen_string_literal: true

class Book < ApplicationRecord

  belongs_to :author
  belongs_to :category
  has_many :ratings
  has_many :order_items

  validates :title, :description, :price, :in_stock, presence: true

  mount_uploader :cover, CoverUploader

  scope :newest, -> { order(created_at: :desc) }
  scope :price_asc, -> { order(:price) }
  scope :price_desc, -> { order(price: :desc) }
  scope :by_title_asc,  -> { order(title: :asc) }
  scope :by_title_desc, -> { order(title: :desc) }
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :books
  validates :title, presence: true, uniqueness: true
end

app/models/coupon.rb
class Coupon < ApplicationRecord
  belongs_to :order, optional: true

  validates :number, presence: true, uniqueness: true
  validates :discount, presence: true
end

app/models/credit_card.rb
class CreditCard < ApplicationRecord
  has_one :order
  validates :number, :cvv, :expiration_month, :expiration_year, :first_name, :last_name, presence: true
end

app/models/delivery_info.rb
class DeliveryInfo < ApplicationRecord
  belongs_to :user
  validates :first_name,
            :last_name,
            :street_1,
            :zip_code,
            :city,
            :region,
            :phone,
            :country, presence: true
  validates :user, presence: true
end

app/models/order.rb
class Order < ApplicationRecord
  include AASM

  belongs_to :user
  belongs_to :credit_card, optional: true
  belongs_to :delivery, optional: true
  belongs_to :billing_address, optional: true
  belongs_to :shipping_address, optional: true
  has_one :coupon, optional: true
  has_many :order_items

  def add_book(book_params)
    current_item = order_items.find_by(book_id: book_params[:book_id])

    if current_item
      current_item.quantity += order_items.find_by[book_id: book_params[:book_id]]
      current_item.save
    else
      order_items.create(
          book_id: book_params[:book_id],
          quantity: book_params[:quantity]
      )
    end
  end

  aasm column: :state do
    state :cart, initial: true
    state :in_delivery, after_enter: :send_confirmation
    state :delivered

    event :deliver do
      transitions from: :in_progress, to: :in_delivery
    end

    event :confirm do
      transitions from: :in_delivery, to: :delivered
    end
  end

  def discount
    coupon ? coupon.discount.to_d : 0
  end

  def calc_total_price
    return self.update(total_price: nil) if self.order_items.empty?
    price = self.order_items.map { |item| item.quantity*item.book.price }.inject(&:+)
    self.update(total_price: price - self.discount)
  end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  include AASM

  belongs_to :book
  belongs_to :order

  validates :quantity, presence: true
  validates :book, presence: true
  validates :order, presence: true

  def subtotal
    book.price * quantity
  end
end

app/models/rating.rb
class Rating < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/street_address.rb
class StreetAddress < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :orders
  has_many :ratings
  has_one :delivery_info
  #validates :name, presence: true
  validates :email, presence: true, format: { with: /.+@.+\..+/i }

  def current_order
    orders.find_or_create_by(state: :cart)
  end

  def load_delivery_info
    return delivery_info if delivery_info.present?
    build_delivery_info
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  # load_and_authorize_resource

  def index
    @books = Book.all
  end

  def show
    @book = Book.find(params[:id]).decorate
    @reviews = Rating.where(book_id: @book.id).order('created_at DESC')
  end

  def newest
    @books = Book.newest
    render action: :index
  end

  def price_asc
    @books = Book.price_asc
    render action: :index
  end

  def price_desc
    @books = Book.price_desc
    render action: :index
  end

  def name_a_to_z
    @books = Book.by_title_asc
    render action: :index
  end

  def name_z_to_a
    @books = Book.by_title_desc
    render action: :index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_order_items_count
    current_order.order_items.count
  end
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_review.haml
.general-message-wrap.divider-lg
  .clearfix
    %span.img-circle.logo-size.inlide-block.pull-left.logo-empty M
    .ml-70
      %div
        .general-message-date.hidden-xs= rating.created_at.strftime("%d/%m/%y")
        .max-240
          .general-message-verified.pull-right Verified Reviewer
          .general-message-name= (rating.decorate.owner.email ? rating.decorate.owner.email : 'John Doe')
      .mb-15
        - rating.rating_number.times do |i|
          %i.fa.fa-star.rate-star
        - (10 - rating.rating_number).times do |i|
          %i.fa.fa-star.rate-star.rate-empty
      %p= rating.review

app/views/books/index.html.haml
%main.container
  %h1.general-title-margin Сatalog
  .hidden-xs.clearfix
    .dropdowns.pull-right
      .dropdown.width-240
        %a.dropdown-toggle.lead.small{href: "#", 'data-toggle': "dropdown",
                                      role: "button", 'aria-haspopup': "true", 'aria-expanded': "false"}
          Filters
          %i.fa.fa-angle-down.dropdown-icon.pull-right
        %ul.dropdown-menu
          %li= link_to "Newest first", newest_books_path
          %li= link_to "Price: Low to high", price_asc_books_path
          %li= link_to "Price: High to low", price_desc_books_path
          %li= link_to "Title: A to Z", name_a_to_z_books_path
          %li= link_to "Title: Z to A", name_z_to_a_books_path
    %ul.list-inline.pt-10.mb-25.mr-240
      %li.mr-35
        = link_to books_path, class: "filter-link" do
          = t('catalog.all_categories')
          %span.badge.general-badge= Book.count
      - Category.all.each do |category|
        %li.mr-35
          = link_to books_path(books_by_category: category.title),
            class: "filter-link" do
            = "#{category.title}"
            %span.badge.general-badge= category.books.count
  .mb-120
    - @books.each_slice(4) do |four_books|
      .row
        - four_books.each do |book|
          = render 'shared/book', book: book.decorate
    .text-center
      %button.btn.btn-primary View More

app/views/books/show.html.haml
%main.container
  %a.general-back-link{href: "#"}
    %a.fa.fa-long-arrow-left.mr-15{href: "#{books_path}"}
    %a.link_to{href: "#{books_path}"} Back to catalog
  .row
    .col-sm-6
      .product-gallery
        .mb-20
          // - if @book.cover.file.nil?
          //   %i.fa.fa-book.fa-4x{ "aria-hidden": true }
          // - else
          = image_tag @book.cover_url(:thumb), class: 'img-responsive'
    .col-sm-6
      %h1.mt-res-0= @book.title
      %p.lead.small= @book.author_name
      .row
        .col-xs-12.col-md-4
          %p.h1.in-gold-500.mt-10= "$ #{@book.price}"
        .col-xs-5.col-md-3
          .input-group.general-position
            %p#minus.input-link
              %i.fa.fa-minus.line-height-40
            %input.form-control.quantity-input{ type: "text", value: '1' }
            %p#plus.input-link
              %i.fa.fa-plus.line-height-40
        .col-xs-7.col-md-5
          %input{ type: 'hidden', value: @book.id, id: 'book-id' }
          %button#add-to-cart.btn.btn-default.pull-right.general-position Add to Cart
      .general-info-wrap.divider-lg
        %p Description
        %p.lead.small.line-height-2
          = @book.description
          %a.in-gold-500.ml-10{href: "#"} Read More
      .general-info-wrap.divider-lg
        .clearfix
          %p.pull-left Year of publication
          %p.lead.small.pull-right 2016
      .general-info-wrap.divider-lg
        .clearfix
          %p.pull-left Genre
          %p.lead.small.pull-right
            = @book.category.title
  .mb-80
    %h3 Write a Review
    %p.general-info-text Score
    .mb-15
      %i.fa.fa-star.rate-empty
      %i.fa.fa-star.rate-empty
      %i.fa.fa-star.rate-empty
      %i.fa.fa-star.rate-empty
      %i.fa.fa-star.rate-empty
      %i.fa.fa-star.rate-empty
      %i.fa.fa-star.rate-empty
      %i.fa.fa-star.rate-empty
      %i.fa.fa-star.rate-empty
      %i.fa.fa-star.rate-empty
    %form.row
      .col-md-8
        .mb-40
          .form-group
            %label.control-label.input-label.in-grey-600{for: "review"} Review
            %textarea#review.form-control{name:"review", type: "text"}
        .text-right
          %button.btn.disabled.mb-20 Post
  .mb-80
    %h3.in-gold-500.mb-25= "Reviews (#{@reviews.count})"
    - @book.ratings.each do |rating|
      = render 'review', rating: rating