config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {
      sessions: 'users/sessions',
      registrations: 'users/registrations'
  }
  resources :books, path: "books" do
    collection do
      get :newest
      get :price_asc
      get :price_desc
      get :name_a_to_z
      get :name_z_to_a
    end
  end

    resources :books, only: :show do
      resources :reviews, only: :create
    end

  resources :categories, only: [:index, :show]
  resources :order_items, only: [:index, :create, :update, :destroy]
  resources :orders, only: [:index, :create, :destroy]
  resources :checkout
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'dashboard#index'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)

    # Define abilities for the passed in user here. For example:
    user ||= User.new # guest user (not logged in)
    #if user.admin?
    #  can :manage, :all
    #else
      can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/author.rb
class Author < ApplicationRecord
  validates :first_name, :last_name, :biography, presence: true
  has_many :books
end

app/models/book.rb
# frozen_string_literal: true

class Book < ApplicationRecord

  belongs_to :author
  belongs_to :category
  has_many :ratings
  has_many :order_items

  validates :title, :description, :price, :in_stock, presence: true

  mount_uploader :cover, CoverUploader

  scope :newest, -> { order(created_at: :desc) }
  scope :price_asc, -> { order(:price) }
  scope :price_desc, -> { order(price: :desc) }
  scope :by_title_asc,  -> { order(title: :asc) }
  scope :by_title_desc, -> { order(title: :desc) }
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :books
  validates :title, presence: true, uniqueness: true
end

app/models/coupon.rb
class Coupon < ApplicationRecord
  belongs_to :order, optional: true

  validates :number, presence: true, uniqueness: true
  validates :discount, presence: true
end

app/models/credit_card.rb
class CreditCard < ApplicationRecord
  has_one :order
  validates :number, :cvv, :expiration_month, :expiration_year, :first_name, :last_name, presence: true
end

app/models/delivery_info.rb
class DeliveryInfo < ApplicationRecord
  belongs_to :user
  validates :first_name,
            :last_name,
            :street_1,
            :zip_code,
            :city,
            :region,
            :phone,
            :country, presence: true
  validates :user, presence: true
end

app/models/order.rb
class Order < ApplicationRecord
  include AASM

  belongs_to :user
  belongs_to :credit_card, optional: true
  belongs_to :delivery, optional: true
  belongs_to :billing_address, optional: true
  belongs_to :shipping_address, optional: true
  has_one :coupon, optional: true
  has_many :order_items

  def add_book(book_params)
    current_item = order_items.find_by(book_id: book_params[:book_id])

    if current_item
      current_item.quantity += order_items.find_by[book_id: book_params[:book_id]]
      current_item.save
    else
      order_items.create(
          book_id: book_params[:book_id],
          quantity: book_params[:quantity]
      )
    end
  end

  aasm column: :state do
    state :cart, initial: true
    state :in_delivery, after_enter: :send_confirmation
    state :delivered

    event :deliver do
      transitions from: :in_progress, to: :in_delivery
    end

    event :confirm do
      transitions from: :in_delivery, to: :delivered
    end
  end

  def discount
    coupon ? coupon.discount.to_d : 0
  end

  def calc_total_price
    return self.update(total_price: nil) if self.order_items.empty?
    price = self.order_items.map { |item| item.quantity*item.book.price }.inject(&:+)
    self.update(total_price: price - self.discount)
  end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  include AASM

  belongs_to :book
  belongs_to :order

  validates :quantity, presence: true
  validates :book, presence: true
  validates :order, presence: true

  def subtotal
    book.price * quantity
  end
end

app/models/rating.rb
class Rating < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/street_address.rb
class StreetAddress < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :orders
  has_many :ratings
  has_one :delivery_info
  #validates :name, presence: true
  validates :email, presence: true, format: { with: /.+@.+\..+/i }

  def current_order
    orders.find_or_create_by(state: :cart)
  end

  def load_delivery_info
    return delivery_info if delivery_info.present?
    build_delivery_info
  end
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.haml
%footer.navbar-inverse
  .container
    .row
      .col-sm-9
        %ul.list-inline.general-align.mb-25
          %li
            %a.nav-link{href: "#"} Home
          %li
            %a.nav-link{href: "#"} Shop
          %li
            %a.nav-link{href: "#"} Orders
          %li
            %a.nav-link{href: "#"} Settings
      .col-sm-3
        %p.general-nav-mail support@bookstore.com
        %p.general-nav-number (555)-555-5555
        %ul.list-inline.general-align
          %li
            %a.nav-link{href: "#"}
              %i.fa.fa-facebook{'aria-hidden': "true"}
          %li
            %a.nav-link{href: "#"}
              %i.fa.fa-twitter{'aria-hidden': "true"}
          %li
            %a.nav-link{href: "#"}
              %i.fa.fa-google-plus{'aria-hidden': "true"}
          %li
            %a.nav-link{href: "#"}
              %i.fa.fa-instagram{'aria-hidden': "true"}

app/views/layouts/_header.html.haml
%header.navbar.navbar-default
  .container
    .navbar-header
      %button.navbar-toggle.pull-left{type: "button", 'data-toggle': "collapse", 'data-target': "#navbar"}
        %span.sr-only
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.navbar-brand{href: "#{root_path}"} Bookstore
      %a.shop-link.pull-right.visible-xs{href: "#"}
        %span.shop-icon
          %span.shop-quantity
            = current_order_items_count
    %a.shop-link.pull-right.hidden-xs{href: "#{orders_path}"}
      %span.shop-icon
        %span.shop-quantity
          = current_order_items_count
    #navbar.navbar-collapse.collapse.pl-30{'aria-expanded': "false"}
      .visible-xs
        %button.close{type: "button", 'aria-label': "Close"}
          %span{'aria-hidden': "true"} &times;
        %ul.nav.navbar-nav
          %li
            %a{href: "#{root_path}"} Home
          %li
            %a{type: "button", 'data-toggle': "collapse", href: "#menu", 'aria-expanded': "false", 'aria-controls': "menu"} Shop
            %ul#menu.collapse.list-unstyled.pl-30.mb-10{'aria-expanded': "false"}
              %li
                %a.collapse-link{href: "#"} Mobile development
              %li
                %a.collapse-link{href: "#"} Photo
              %li
                %a.collapse-link{href: "#"} Web design
      .hidden-xs
        %ul.nav.navbar-nav
          %li
            %a{href: "#{root_path}"} Home
          %li.dropdown
            %a.dropdown-toggle{href: "#", 'data-toggle': "dropdown", role: "button", 'aria-haspopup': "true", 'aria-expanded': "false"} Shop
            %ul.dropdown-menu
              %li
                %a{href: "#"} Mobile development
              %li
                %a{href: "#"} Photo
              %li
                %a{href: "#"} Web design
              %li.divider{role: "separator"}
              %li
                = link_to 'Log out', destroy_user_session_path, method: :delete
          %li
            %a{href: "#"} My account
          %li
            %a{href: "#{new_user_session_path}"} Log in
          %li
            %a{href: "#{new_user_registration_path}"} Sign up

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Bookstore
    %meta{charset: "UTF-8"}
    %meta{name: "viewport", content: "width=device-width"}
    %link{href: "https://fonts.googleapis.com/css?family=Open+Sans", rel: "stylesheet"}
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    %script{src: "https://use.fontawesome.com/67602d7308.js"}
  %body
    = render partial: "layouts/header"
    -#= render partial: "layouts/flash_message"
    = yield
    = render partial: "layouts/footer"

app/views/shared/_book.haml
.col-xs-6.col-sm-3
  .general-thumb-wrap
    .thumbnail.general-thumbnail
      = image_tag book.image_cover_url, class: 'img-shadow general-thumbnail-img', alt: 'design-book'
      .thumb-hover
        .general-thumb-link-wrap
          = link_to book_path(book.id), class: "thumb-hover-link" do
            %i.fa.fa-eye.thumb-icon{ 'aria-hidden': "true" }
          %a.thumb-hover-link{href: "#"}
            %i.fa.fa-shopping-cart.thumb-icon
  .general-thumb-info
    %p.title= book.title
    %p.font-16.in-gold-500= "$ #{book.price}"
    %span.divider-sm
    %p.lead.small= book.author_name